/*

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

*/

const generateTriNums = (terms) => {
  let results = [];
  let count = 1;
  while (count <= terms) {
    let result = (count * (count + 1)) / 2;
    results.push(result);

    count++;
  }
  return results;
}
const generatePentNums = (terms) => {
  let results = [];
  let count = 1;
  while (count <= terms) {
    let result = (count * ((3 * count) - 1)) / 2;
    results.push(result);

    count++;
  }
  return results;
}
const generateHexNums = terms => {
  let results = [];
  let count = 1;
  while (count <= terms) {
    let result = count * ((2 * count) - 1);
    results.push(result);

    count++;
  }
  return results;
}

const TRI_NUMS = generateTriNums(100000);
const PENT_NUMS = generatePentNums(100000);
const HEX_NUMS = generateHexNums(100000);

const findTheTerms = () => {
  let results = [];
  for (let i = 0; i < TRI_NUMS.length; i++) {
    if (PENT_NUMS.indexOf(TRI_NUMS[i]) !== -1) {
      if (HEX_NUMS.indexOf(TRI_NUMS[i]) !== -1) {
        results.push(TRI_NUMS[i]);
      }
    }
  }
  return results;
}

console.log(findTheTerms());