/*

Pentagonal numbers are generated by the formula, P(n)=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P(4) + P(7) = 22 + 70 = 92 = P(8). However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P(j) and P(k), for which their sum and difference are pentagonal and D = |P(k) − P(j)| is minimised; what is the value of D?

*/

const generatePentagonals = (terms) => {
  let results = [];
  let count = 1;
  while (count <= terms) {
    let result = (count * ((3 * count) - 1)) / 2;
    results.push(result);

    count++;
  }
  return results;
}

const PENTAGONALS = generatePentagonals(3000);
const isPentagonal = num => true ? PENTAGONALS.indexOf(num) !== -1 : false;

const findPentagonals = () => {
  results = {};
  for (let i = 0; i < PENTAGONALS.length - 1; i++) {
    for (let j = (i + 1); j < PENTAGONALS.length; j++) {
      let sum = PENTAGONALS[i] + PENTAGONALS[j];
      let diff = PENTAGONALS[j] - PENTAGONALS[i];
      if (isPentagonal(sum) && isPentagonal(diff)) {
        results.sum = sum;
        results.diff = diff;
        results.i = PENTAGONALS[i];
        results.j = PENTAGONALS[j];
      }
    }
  }
  return results;
}

console.log(isPentagonal(4187));
console.log(findPentagonals());